export const ADD_GRADE_ERROR = 'ADD_GRADE_ERROR';
export const ADD_GRADE_LOADING = 'ADD_GRADE_LOADING';
export const ADD_GRADE_SUCCESS = 'ADD_GRADE_SUCCESS';

export const UPDATE_GRADE_ERROR = 'UPDATE_GRADE_ERROR';
export const UPDATE_GRADE_LOADING = 'UPDATE_GRADE_LOADING';
export const UPDATE_GRADE_SUCCESS = 'UPDATE_GRADE_SUCCESS';


export const FETCH_GRADE_ERROR = 'FETCH_GRADE_ERROR';
export const FETCH_GRADE_LOADING = 'FETCH_GRADE_LOADING';
export const FETCH_GRADE_SUCCESS = 'FETCH_GRADE_SUCCESS';


export const FETCH_BY_ID_GRADE_ERROR = 'FETCH_BY_ID_GRADE_ERROR';
export const FETCH_BY_ID_GRADE_LOADING = 'FETCH_BY_ID_GRADE_LOADING';
export const FETCH_BY_ID_GRADE_SUCCESS = 'FETCH_BY_ID_GRADE_SUCCESS';

export const DELETE_GRADE_ERROR = 'DELETE_GRADE_ERROR';
export const DELETE_GRADE_LOADING = 'DELETE_GRADE_LOADING';
export const DELETE_GRADE_SUCCESS = 'DELETE_GRADE_SUCCESS';