export const ADD_SL_ERROR = 'ADD_SL_ERROR';
export const ADD_SL_LOADING = 'ADD_SL_LOADING';
export const ADD_SL_SUCCESS = 'ADD_SL_SUCCESS';

export const UPDATE_SL_ERROR = 'UPDATE_SL_ERROR';
export const UPDATE_SL_LOADING = 'UPDATE_SL_LOADING';
export const UPDATE_SL_SUCCESS = 'UPDATE_SL_SUCCESS';


export const FETCH_SL_ERROR = 'FETCH_SL_ERROR';
export const FETCH_SL_LOADING = 'FETCH_SL_LOADING';
export const FETCH_SL_SUCCESS = 'FETCH_SL_SUCCESS';


export const FETCH_BY_ID_SL_ERROR = 'FETCH_BY_ID_SL_ERROR';
export const FETCH_BY_ID_SL_LOADING = 'FETCH_BY_ID_SL_LOADING';
export const FETCH_BY_ID_SL_SUCCESS = 'FETCH_BY_ID_SL_SUCCESS';

export const DELETE_SL_ERROR = 'DELETE_SL_ERROR';
export const DELETE_SL_LOADING = 'DELETE_SL_LOADING';
export const DELETE_SL_SUCCESS = 'DELETE_SL_SUCCESS';