export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_USER_LOADING = 'ADD_USER_LOADING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';


export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';


export const FETCH_BY_ID_USER_ERROR = 'FETCH_BY_ID_USER_ERROR';
export const FETCH_BY_ID_USER_LOADING = 'FETCH_BY_ID_USER_LOADING';
export const FETCH_BY_ID_USER_SUCCESS = 'FETCH_BY_ID_USER_SUCCESS';

export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';